// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cufatgqkaodclrbzcvdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1ZmF0Z3FrYW9kY2xyYnpjdmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDUzMTYsImV4cCI6MjA3MDQ4MTMxNn0.YAv4xU1dZV-7u_FicFSLzhBLyh2pKvOaXfw_ZiRmPZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});